"""Blob storage on local disk (replaces public Firebase Storage objects).

Keys are generated by the server (``new_key``), never taken from a client filename.
Every key is resolved under ``root`` and rejected if it would escape it.
"""

from __future__ import annotations

import os
import re
import tempfile
import uuid
from pathlib import Path
from typing import BinaryIO, Protocol, runtime_checkable

_KEY_SEGMENT = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")


@runtime_checkable
class BlobStore(Protocol):
    def put(self, key: str, data: bytes) -> None: ...

    def open(self, key: str) -> BinaryIO: ...

    def delete(self, key: str) -> None: ...

    def exists(self, key: str) -> bool: ...


def new_key(*prefix: str, suffix: str = "") -> str:
    """Build a server-side key such as ``pets/<pet>/records/<uuid>.pdf``."""
    if suffix and not re.fullmatch(r"\.[A-Za-z0-9]{1,8}", suffix):
        raise ValueError(f"invalid blob suffix {suffix!r}")
    return "/".join([*prefix, f"{uuid.uuid4().hex}{suffix}"])


class LocalBlobStore:
    def __init__(self, root: Path | str) -> None:
        self.root = Path(root).resolve()

    def _resolve(self, key: str) -> Path:
        parts = key.split("/")
        if not parts or any(not _KEY_SEGMENT.match(part) for part in parts):
            raise ValueError(f"invalid blob key {key!r}")
        target = (self.root / Path(*parts)).resolve()
        if self.root not in target.parents:
            raise ValueError(f"blob key {key!r} escapes the blob root")
        return target

    def put(self, key: str, data: bytes) -> None:
        target = self._resolve(key)
        target.parent.mkdir(parents=True, exist_ok=True)
        fd, tmp_name = tempfile.mkstemp(prefix=".blob-", dir=target.parent)
        try:
            with os.fdopen(fd, "wb") as fh:
                fh.write(data)
            os.replace(tmp_name, target)
        except BaseException:
            try:
                os.unlink(tmp_name)
            except OSError:
                pass
            raise

    def open(self, key: str) -> BinaryIO:
        return self._resolve(key).open("rb")

    def delete(self, key: str) -> None:
        try:
            self._resolve(key).unlink()
        except FileNotFoundError:
            pass

    def exists(self, key: str) -> bool:
        return self._resolve(key).is_file()
